### PR TITLE
Issue #145 - Use the modern save file dialog

### PR DESCRIPTION
**Pull request by opello**
Support using the CommonOpenFileDialog as a folder picker when choosing directories.  This behavior relies on the Windows API Code Pack which is provided by NuGet.  Since this dialog is only available on Vista and later a test which will fall back to the older Windows Forms dialog is included.

I welcome your review and any feedback you might have.

### CODE REVIEW

**Comment by Franiac** [comment]
Thx for the contribution. I dislike the Microsoft Nuget because it had some major bugs in the past, but the FolderBrowser dialog seems to work well, so we'll keep the reference.

I fixed 2 things:

1. The CommonOpenFileDialog implements IDisposable and therefor needs manual disposal. I added the using around it accordingly. I case of an exception (see 2.) there can be a memory leak.

2. If you cancel the dialog, you cannot read from cofd.FileName. That results in an unhandled exception. Always try every possibility when testing :)

Take a look at it. If you agree, I accept the pull request.

**Comment by Franiac** [comment]
Oh and a 3rd thing:

Since TL depends on the 2 new dll's, we need to add those to the installer. But you cannot know this if you are not into WiX/MSI Installer stuff :)

**Comment by opello** [comment]
Thanks for taking a look at it.  I'm certainly fine with these changes, sorry for missing the IDisposable thing.  I remember looking but must have missed it.  I didn't consider the installer at all either, oops!

I'm curious about the IsPlatformSupported test and why you used the CommonFileDialog class to access it instead of the CommonOpenFileDialog?

Should I do anything as far as squashing these commits together or what is your preference for that?

**Comment by Franiac** [comment]
IsPlatformSupported is just something the code analyze tool of VS showed me. The reason is, IsPlatformSupported  is not implemented in CommonOpenFileDialog, it is just derived from CommonFileDialog. So this changes nothing, but I like to keep things clean regarding the VS code analysis tool.

You don't need to do anything, I can just merge the pull request now. I basically commited the changes to your pull request.

**Pull request merged**
