### PR TITLE
Auto split

### PR DESCRIPTION
**Pull request by targen92**
There are 5 commits:
Show filename, crop time in downloads tab.
Add 3 new wildcards with hyphen.
Add special wildcard, that will be replaced by some number to avoid overwrite.
Add new settings option - quality by default. Will be selected ONLY if this quality exist, in other cases you has to select quality manually (as now).
Add autosplit option (with special setting in preferences). You can download video by part automatically, with extra overlap option. Work only with conversation.

This is almost same changes, full tested

### CODE REVIEW

**Comment by targen92** [comment]
Also i made more options for live stream: update total video length, download while previous video is concatenating and wait till stream end with downloading it by parts.

**Comment by Franiac** [comment]
@targen92 you can make an additional PR for the other features if you like

**Comment by andromedaark** [comment]
Would it be possible to include a drop down option on the download to download the audio to a mp3 in future releases please.

Thanks

**Comment by Rook25** [comment]
@targen92 I'm looking at downloading over 1000 videos from my personal twitch channel to archive and your 'auto quality' option will really help with this. Even though this is a bit older, should it be possible to integrate into the latest release?

**Comment by Franiac** [comment]
Since I am planning to switch TL to Electron / Angular I won't implement those features here.

**Pull request closed without merging**
