### PR TITLE
Added support for sub-only VODs with auth-token

### PR DESCRIPTION
**Pull request by CrizGames**

### CODE REVIEW

**Comment by Effanuel** [comment]
Looking forward to this

**Comment by HeyMika** [comment]
Already tested it out and it works flawless. Encountered no issues yet, just needs to be pulled now.

**Comment by Effanuel** [comment]
> Already tested it out and it works flawless. Encountered no issues yet, just needs to be pulled now.

Hey, can you compile an executable and share it? My old laptop throws errors while building

**Comment by CrizGames** [comment]
I uploaded a build on my fork: https://github.com/CrizGames/TwitchLeecher/releases/tag/v1.8.5

**Comment by Franiac** [comment]
Cool that it works again, but here's why I won't accept this particular PR:

1. 80% of TL users cannot explain what a cookie is
2. 90% of TL users don't know what browser developer tools are or how to deal with it (and they should not know)
3. 100% of TL users should be able to use the feature without asking weird questions about how to get that token
4. A token is not part of sofware "Preferences"
5. A token expires and there's no check for it
6. A token needs re-validation on every program start and there is none
7. A token can be revoked and the user cannot do it in this implementation
8. We need a proper login dialog like TL 1.7.x (before sub-only was removed) to get the token and save it to a runtime configuration file (again like in TL 1.7.x)
9. The user should never ever see tha token. The handling should entirely masked by the application

This PR is a (working) workaround and it's gret for IT-people or gamers that "know stuff". But average Joe won't be happy with it and we need to make average Joe happy, too.

Here is what I am going to do:

1. Reject this PR
2. Use the PR's code to implement sub-only support again (so the PR is not useless or not appreciated)
3. Include CefSharp (Chromium engine) into TL (will make it 130MB bigger but who cares)
4. Implement a login form for average Joe
5. Implenent token handling (re-validation, expiration checks and the ability to revoke the token) for average Joe

I know you know I have not a lot of time to spend on TL but I see the need for sub-only downloads. I will give my best to re-implenent this feature shortly. I hope you can understand my argumentation. The priority of a feature shoud not be the feature itself but the user using it.

Anyway, thank you for this PR, we will make it work properly...

**Comment by Effanuel** [comment]
Totally agree with Franiac. If this is implemented, it should be done properly.

**Comment by CrizGames** [comment]
Yeah your're right. Looking forward to your implementation!

**Comment by Franiac** [comment]
Guys, I need help!

I am running into an exception if I use an access token in TwitchService -> RetrieveVodAuthInfo but the video is NOT sub-only. This should also throw an error in this PR. Have you tried that? Using a valid access token on normal videos?

Please check my new branch "subonly" next to master. You can get an auth token via the Twitch symbol in the title bar. Connect TL and try downloading normal videos -> does not work.

Could someone check if my implementation works for sub-only videos? I am not subscribed to anyone who has sub-only videos.

The issue is TwitchService line 211.

**Comment by Franiac** [comment]
Ok here's something super fucky:

If I authorize TL via the integrated browser I get an auth token that throws an exception when downloading non-sub-only videos.

If I hardcode the auth token from the browser (not the one from TL) it works. SO basically the browser auth token seems to be something different than the auth token you get from the official authorization API.

**Comment by Franiac** [comment]
Ok, I needed to use `Authorization: Bearer <token>` instead of `Authorization: OAuth <token>`

That's interesting. The token from the website needs OAuth, the token from the API needs Bearer.... LOL

**Comment by Franiac** [comment]
You can test the new implementation:

Please see my comment on #531 and use the issue for further conversation. This PR is now obsolete.

**Pull request closed without merging**
