### PR TITLE
Autosplit, default quality, some wildcards and info in downloads tab

### PR DESCRIPTION
**Pull request by targen92**
There are 5 commits:
Show filename, crop time in downloads tab.
Add 3 new wildcards with hyphen.
Add special wildcard, that will be replaced by some number to avoid overwrite.
Add new settings option - quality by default. Will be selected ONLY if this quality exist, in other cases you has to select quality manually (as now).
Add autosplit option (with special setting in preferences). You can download video by part automatically, with extra overlap option. Work only with conversation.

### CODE REVIEW

**Comment by MishManners** [comment]
Downloading video parts would be very useful!

**Comment by Franiac** [comment]
I have a few questions. I saw you are publishing releases on your repo (TL 1.7.1). This is all good and MIT license is exactly for that. But you started to change the readme links and author information in this pull request.

So my question is: Are you working on your own version of TL? Because if so, you should definitely rename the App to Targen's Twitch Leecher or else so everyone knows what they're dealing with. Because if you publish TL 1.7.1 and I do the same in a couple weeks, installations will eventually clash on the user's system.

So if you are working on a complete new feature rich TL, you should stop commiting changes like versioning and author information in this pull request and separate your repository.

As a hint: In order to separate the installers, you'll need to create new product and upgrade codes in the installer project. Otherwise Windows installer will throw errors at you on your next release. Basically you will need to tell Windows that your TL is a different one than mine.

I can merge festures into this repo, but not author information and versioning. So if you want to have your features in the original TL, you should create a new pull request for each feature separately without changing any of the original readmes and version information. Those have no place in a PR.

Compare it to StreamLabs OBS and OBS Studio. StreamLabs forked OBS and made it their own software. Separate installer, separate versioning and such. So what am I looking at here? Do you want to go ahead and create your own TL or do you want the features merged?

Because if it's option #2, I cannot really merge your PR anymore. I don't want to cherry pick myself through the commit list. We need every feature separately testable in a separate PR. At least that's what I am used to on GitHub.

I am really happy to see that there is some action going on with TL but we need to arrange ourselves depending on what your plans with the software are 😄

**Comment by targen92** [comment]
@Franiac First of all, I apologize for my mistakes. I have almost no experience in development, commiting and publishing. So please let me know if i can do something in better ways.
I want to add all those enhancements to your application. But, as i see, you do a lot of tests and don't want to add so big changes.
Now i undestand your concerns and I am going to rework my fork to split if in two branches - with commits that can be merged with your application and same branch with own guid, releases and name to let anybody install my version of TL.
So i have question - should i do a pull request to every commit? And how i should orginize my work to leave possibility to merge it with your application?
Also, I would like to have faster way to contact with you, because i have some more ideas to improve TL

**Comment by Franiac** [comment]
@targen92 Hey, no problem at all, we all start somewhere.

So here's how it goes usually:

Basically a pull request is a branch of your forked repo that you want to have merged into my master branch. If you develop a new feature, the PR should be self-contained on submission. That means you have thoroughly tested everything, don't have any conflicts and everything needed has been committed in the PR branch.

You should not develop on an open PR unless the receiver (me) tells you there's something that needs improvement or you spot a bug and want to fix it (which should not happen if you tested everything 😄).

There should not be more than one feature in a single PR, because if one feature is ok and the other is not I cannot merge the good feature because it is together with another feature that might need improvements. This is the case with this PR. I don't like certain things but i also cannot merge other features until the bad ones are fixed. I hope that makes sense.

The rule is: One feature = one PR. You open up a new branch for every new feature that you want to submit. Sure, If features depend on each other you have to put them in a single branch but that's not very common.

And again, do NOT "develop" on an open PR. A PR is a COMPLETE and FINISHED feature ready for merging. Once sumbitted you should be finished and be be like "oh, I also could do that and that". Because if I get a PR and test it and 5 hours later there's a new commit and I have to test everything again.... well... that's not fun 😄 

Now something basic and I really don't want to speak badly of you:

Your code needs improvements in a couple of areas. I see that you are farely new and this is perfect, noone can be an expert right off the bat. BUT! The time that I would need to clean your code or give you hints for improvements, I basically can implement the thing by myself. That's not made up in order to screw you over (I don't do such a thing) that's just how it is. I really don't have that much time to invest into TL. And if I start to spend all that time into fixing PR's, TL will get nowhere.

I love your improvements and I will surely adapt the code but don't be angry if I implement certain features myself and decline your PR because it simply is faster if I do it on my own. You can be sure that I take a look at your implementations to see what you have there and probably will use code you have written so it is a great help from you.

Now here's what we do:

You should not make anymore commits to this PR. But also you don't need to split this into separate PR's. I can use this PR as it is and it is very valuable for my own implementations. If you have new implementations just make sure that they are separate well tested PR's as described above without changing stuff that is not related to the feature (author info, versions and such).

A quick hint: I am working on the new download manager right now that is not in the TL repo. That's why there is nothing going on right now in TL. Just for your info.

Also when that's done I am looking forward to port TL into an Electron app based on Typescript/HTML5/SCSS/NodeJS because then TL is Linux and Mac compatible. I don't really like .NET and C# so TL will transform into a desktop Angular application in the forseeable future. But there's not really more info about that at the moment.

I hope this all helps you a little bit and again, don't be pissed if I cannot handle your PR's in time but be sure they are useful and help implementing features 😄

**Pull request closed without merging**
