### PR TITLE
Added ability to use external player to open video streams

### PR DESCRIPTION
**Pull request by schnema123**
Hello

Personally ive found that the twitch video streams do not work reliably for me. Thats why I added the possibility to use an external video player for opening the streams instead of opening them in the web browser. This works very good for VLC, and the code I have added does the job for me.

If you want to merge this code probably must be polished a bit.

Greetings

### CODE REVIEW

**Comment by schnema123** [comment]
Thats what i meant by polishing it a bit.

I thought that I could add another textbox in the preferences. "Arguments" or something like that where you can list the needed arguments for the external player. Where for example {url} is substituted with the url.

But to be honest, i dont know any other video player that is used as much as vlc... Also, how many of them would be able to parse a twitch url? An alternative would be making this feature only available for VLC?

**Comment by Franiac** [comment]
I am on it right now. I think I actually add that textbox...

What I also dislike is that if you disable the checkbox, the other controls disappear. That's bad from a user's perspective. Disabling controls is much more convenient.

**Comment by Franiac** [comment]
Opening VLC 2.2.1 with

`vlc.exe https://www.twitch.tv/videos/99905481`

doesn't do anything.... I going to check out version 3...

**Comment by Franiac** [comment]
Ok, VLC 3 seems to work

**Comment by schnema123** [comment]
The alternative would be to make it work with more media players:

Download the m3u8 for the quality you want and fix it (append the urls in front of the file names). After that you can open the file in VLC.

I've done this in python and it should work for VLC2 also... but I don't if its worth the hassle


```
import sys
import requests
import re
import vlc_wrapper

ACCESS_TOKEN = "https://api.twitch.tv/api/vods/{}/access_token"
M3U8 = "https://usher.ttvnw.net/vod/{}?nauthsig={}&nauth={}&allow_source=true&player=twitchweb&allow_spectre=true&allow_audio_only=true"

class quality_group():

    def __init__(self, bandwidth, url):
        self.bandwidth = bandwidth
        self.url = url

def get_best_quality_url(id):
    access_token_request = ACCESS_TOKEN.format(id)
    access_token_request_headers = {'Client-ID': "xxx"}
    access_token = requests.get(access_token_request, headers=access_token_request_headers).json()

    token = access_token["token"]
    sig = access_token["sig"]

    m3u8_request_string = M3U8.format(id, sig, token)
    m3u8 = requests.get(m3u8_request_string).text

    m3u8_lines = m3u8.split("\n")
    bandwidth_re = re.compile(r"BANDWIDTH=([\d]+)")

    qualities = []

    for i, line in enumerate(m3u8_lines):
        if line.startswith("#EXT-X-STREAM-INF:"):
            bandwidth_re_match = bandwidth_re.search(line)        
            bandwidth = int(bandwidth_re_match.group(1))
            url = m3u8_lines[i+1]
            qualities.append(quality_group(bandwidth, url))

    best_quality = max(qualities, key=lambda q: q.bandwidth)
    return best_quality.url

def get_fixed_m3u8(url):

    url_without_file = url[:url.rfind("/") + 1]

    lines_full = requests.get(url).text
    lines = lines_full.split("\n")
    fixed_lines = []

    for line in lines:
        if ".ts" in line:
            fixed_lines.append(url_without_file + line)
        else:
            fixed_lines.append(line)

    return "\n".join(fixed_lines)

def main():
    video_id = sys.argv[1]
    best_quality_url = get_best_quality_url(video_id)
    m3u8 = get_fixed_m3u8(best_quality_url)

    fille_name = "./streams/" + video_id + ".m3u8"
    m3u8_file = open(fille_name, "w")
    m3u8_file.write(m3u8)
    vlc_wrapper.play_file(fille_name)

if __name__ == "__main__":
    main()
```

**Comment by Franiac** [comment]
Honestly I think that's overkill. Not many users use TL as a "video browser" and actually click on the video to watch it. Downloading is the main concern and usually hte users know exactly what they want when they open up TL.

I am correcting some things right now and ditch the arguments textbox... works for VLC 3 and I mention that in the help tooltip that this is is the preferred way to go. If anyone is unhappy with the feature, we'll get a issue sooner or later anyways 😄

**Comment by Franiac** [comment]
Is just don't want to spend more time on the feature knmowing it could be sufficient the way it is (which would be great)

**Comment by Franiac** [comment]
I am done with the changes... you can take a look at it. I'll merge it later and release 1.5.1 because I need to fix 2 bugs in 1.5

**Comment by schnema123** [comment]
This is exactly the way to go. Having it work with VLC3 only does the job for most users who want to use this feature. Great changes to my code from you. Thank you. 👍

**Comment by schnema123** [comment]
One little thing that I noticed: Since you made a new section "Misc" in the preferences maybe I could rename AppUseExternalPlayer in preferences to MiscUseExternalPlayer since i thought the naming was based on sections?

**Comment by Franiac** [comment]
Good point... let me do that real quick, I'll merge in a second

**Comment by Franiac** [comment]
Well... NOW we're done I think

**Comment by Franiac** [comment]
🎉

**Comment by schnema123** [comment]
Nice catch! Good one.

**Pull request merged**
