### PR TITLE
Restored sub-only support to 1.8.4

### PR DESCRIPTION
**Pull request by davepusey**
Restored sub-only support, and added sub-only indicator to search results.

Based on release version 1.8.4 (commit 0224523f0b6816fc4ac0d41ae4e24c78ecc3867d)

### CODE REVIEW

**Comment by Franiac** [comment]
I am confused honestly... this cannot work at all and it does not. Tested on a channel I am subbed to, getting 403 (Forbidden) exceptions on sub-only videos. I expected this to happen as soon as I saw the code changes.

I don't understand how you could be able to download a sub-only video without authentication and authorization (token). You cannot check if the user is subbed to any channel without a proper login (like in my "subonly" branch).
The usher endpoint (where you get the playlist from) needs a valid OAuth token that tells it that the token owner (user) is a subscriber to the channel, otherwise it will not download anything. And that's exactly the issue here and what we are struggling with in #531.

I really appreciate the work and the will to contribute, but either I am missing something here or this simply does not do what it is supposed to do.

**Comment by davepusey** [comment]
I tested it myself against the kurtjmac channel, which I am subbed to and know for a fact is in sub-only mode, and it worked perfectly.

Can you let me know which channel you tried so that I can test that too please?

**Comment by davepusey** [comment]
Also, I'm using VIDEO_URL to get the VOD metadata, not whatever "usher" is.

**Comment by davepusey** [comment]
Ok, just tried it on another video from that channel and that worked too...

[TL_Log_1161407406.txt](https://github.com/Franiac/TwitchLeecher/files/7291643/TL_Log_1161407406.txt)

Looks like it works for Broadcasts, but not Highlights. I will investigate furthur and keep you posted.

**Comment by Franiac** [comment]
> (Firstly, it is already well beyond Feb 2021, and the Twitch website is still using V5)

I mean 2022. See [HERE](https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/?utm_referrer=https://dev.twitch.tv/)

**Comment by davepusey** [comment]
And we can look at API migrations another time. The focus here was to restore previous functionality that was desperately needed.

**Comment by Franiac** [comment]
I can confirm that it works (which I do not understand and am very very very suspicious about). Sure, the animated preview also workes for non-subbed users just to get a glimpse of the video, but we cannot introduce a feature that has a lifetime of 4 months.

Also there is another thing to consider: In your PR non-sub-only videos now use the `animated_preview_url`, too.
So on February 7th 2022 TL will stop working entirely.

I don't have a good feeling about this.

Please also see my comment [HERE](https://github.com/Franiac/TwitchLeecher/issues/531#issuecomment-935763019)

**Comment by davepusey** [comment]
I agree that it is not a viable long term solution, but it is at least better than nothing.

I am intending to look into the new Twitch API and work on a variant of this method that will work for that API too.

**Pull request closed without merging**
